# Generated by Django 5.2.1 on 2025-06-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(default='', max_length=300, verbose_name='Descrição'),
        ),
    ]
