# Generated by Django 5.2.1 on 2025-06-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_itempedido_preco_unitario_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
